### PR TITLE
chore: remove mongosh formula since it is part of homebrew-core MONGOSH-806

### PR DESCRIPTION
**Pull request by rose-m**
The `mongosh` formula is now part of `homebrew/core` - see: https://github.com/Homebrew/homebrew-core/pull/78239.

We should therefore remove it from here.

### CODE REVIEW

**Comment by acmorrow** [comment]
@rose-m - This LGTM mechanically, but I do have a question. What is the user experience here if someone had a prior install of `mongosh` from this repo? When they update `homebrew-core` and this tap, will they be stranded on the last version they obtained from this repo until they do an uninstall/re-install cycle? Is there some sort of transitional step we should be taking? Or will `homebrew` sort it out for them?

**Review by acmorrow — APPROVED** [review]

**Comment by rose-m** [comment]
Thanks @acmorrow - true there is an issue with people having it installed from our tap already. You'll have to uninstall it first and then you're able to install it from `homebrew/core`. I'll make sure we'll get that put in the docs.

**Comment by max-ae** [comment]
You can also create a tap_migrations.json file.

https://docs.brew.sh/Migrating-A-Formula-To-A-Tap

Have a look at https://github.com/Homebrew/homebrew-core/blob/master/tap_migrations.json

**Comment by rose-m** [comment]
@max-ae awesome, good to know! I've added that to the PR 👍

**Pull request merged**
