### PR TITLE
Remove $ prefix from shell commands

### PR DESCRIPTION
**Pull request by sidharthv96**
The $ will cause issues when using the copy code button introduced in github recently.

### CODE REVIEW

**Comment by iamalisajid** [comment]
👍 for this.

**Review by acmorrow — APPROVED** [review]

**Comment by acmorrow** [comment]
@sidharthv96 - I'm inclined to merge this, but I did want to ask if you might know of another annotation, which would present the `$` on the screen for the purpose of making it clear when reading that the intended context is a shell session, but would not copy the `$` when the copy button was pressed?

**Comment by sidharthv96** [comment]
Hmm, I'm not aware of any such syntax. When I worked on the PR to add copy
button on brew website https://formulae.brew.sh/formula/git , I had to
write custom JS to avoid the $.

So unless GitHub provides a functionality, I don't think we have
another option.

The preceding text and code block formatting might be good enough for most
users.

**Comment by acmorrow** [comment]
@sidharthv96  - Merged. Thank you for the PR!

**Pull request merged**
