### PR TITLE
update 5.0 release

### PR DESCRIPTION
**Pull request by dmoody256**

### CODE REVIEW

**Review by deriamis — APPROVED** [review]
LGTM

**Comment by al-cheb** [comment]
@deriamis, @dmoody256, Why did you decide to update to the release candidate instead of release?

**Comment by dmoody256** [comment]
> @deriamis, @dmoody256, Why did you decide to update to the release candidate instead of release?

@al-cheb 5.0.0-rc0 is a release candidate for testing & not for production and we are releasing it as part of our new rapid release cadence. https://developer.mongodb.com/community/forums/t/mongodb-5-0-0-rc0-is-released/108893

Continue to use mongodb-community@4.4 for the latest production release. I'll update the readme to make this more clear.

**Comment by dmoody256** [comment]
@al-cheb your question did flow up and raised some concerns so we decided to exclude homebrew from this rapid release cadence so we reverted the 5.0 update. When the official 5.0 release is ready the homebrew will be updated.

**Comment by andf-mongodb** [comment]
Hi. Can you update as to status of the above comment, given release of 5.0 yesterday? Thank you

**Pull request merged**
