### PR TITLE
Switch to modern service definition

### PR DESCRIPTION
**Pull request by gwynne**
Homebrew has officially deprecated the `plist_options` command, causing various invocations of `brew` (including many that don't reference MongoDB at all) to issue noisy warnings for each mongodb formula, e.g.:

```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the mongodb/brew tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/mongodb/homebrew-brew/Formula/mongodb-community.rb:55
```

The deprecation message refers to the `service.require_root` option, but that suggestion applies to the use of `plist_options :startup`. For `plist_options :manual` as used by the MongoDB formulae, the expected course of action is to remove the manually specified plist entirely and specify an equivalent `service` block. At this time, there is no way to specify the `Hard/SoftResourceLimits` options in a `service` block, but the default limits for a properly configured service on macOS Monterey and Ventura appear to already be adequate (per the output of `sysctl kern.maxfiles{,perproc}`), so I haven't made any effort to address it for now.

The `service` block generates a correctly configured plist on macOS; it should also generate a working service file on Linux (although I did not test that).

(Note: The explicit deprecation message only appears for those running Homebrew at HEAD, and has been temporarily reverted due to unrelated problems caused by other changes made in the same commit, but is scheduled to be re-enabled in the upcoming 3.7.0 release. It's my understanding that switching to `service` blocks has been the recommendation for quite a while now, and if there _is_ an issue due to the resource limits concern, tackling this now improves the chances that Homebrew can add additional support upstream before the deprecation warnings start showing up for all users.)

References:
https://github.com/Homebrew/homebrew-core/pull/121456
https://docs.brew.sh/Formula-Cookbook#service-files
https://github.com/Homebrew/brew/pull/14382
https://github.com/Homebrew/brew/pull/14548
https://github.com/Homebrew/brew/issues/14542

### CODE REVIEW

**Review by dkbhadeshiya — APPROVED** [review]

**Comment by dmoody256** [comment]
Thanks for the pull request! We considered the option of using brew's service block to generate service files, and we decided we would rather keep the ability to leverage the MacOS launchd options provided via plist. 

We are working to move the plist into our macos tarballs and update the formulae to install the plist via `prefix.install_symlink "file.plist" => "#{plist_name}.plist"` for launchd. We don't currently have plans to support installing MongoDB via homebrew on linux. 

You can track the work for this in our issue tracker: https://jira.mongodb.org/browse/SERVER-74025.

**Comment by lucasefe** [comment]
This PR creates a regression. Mongodb service starts crushing with "Too Many Files Open" after a while. 
I believe it happens because the generated plist file no longer includes the following:

```
      <key>HardResourceLimits</key>
      <dict>
        <key>NumberOfFiles</key>
        <integer>64000</integer>
      </dict>
      <key>SoftResourceLimits</key>
      <dict>
        <key>NumberOfFiles</key>
        <integer>64000</integer>
      </dict>
```

Not sure what the plan is for this.

**Comment by gwynne** [comment]
@lucasefe https://github.com/mongodb/homebrew-brew/pull/174#issuecomment-1433316812 explains how this will be addressed, IIUC

**Comment by lucasefe** [comment]
Okey, but for now it's broken, right? 

We are currently loading the previous plist service file using the `--file` option, like so:

```
brew services start mongodb-community@6.0 --file homebrew.mxcl.mongodb-community.plist
```

**Comment by dmoody256** [comment]
@lucasefe There are several things you can do until the next release that includes the plist file. You can:

1. Increase your MacOS system defaults for file limits, the method to do this will depend on your MacOS version, newer MacOS should already be sufficiently high, so you could also try upgrading your MacOS.
2. You can copy the brew generated plist file you were using in your previous comment, modify it to include the properties you mentioned, and then load this plist via the --file command like you were doing in your previous comment.

**Comment by crimsonvspurple** [comment]
> @lucasefe [#174 (comment)](https://github.com/mongodb/homebrew-brew/pull/174#issuecomment-1433316812) explains how this will be addressed, IIUC

Hello.

The linked comment links to an issue that has been marked resolved long ago. My plist still doesn't contain the resource limit key/values and whole server was crashing in the middle of usage (dev; only 40MB db).

The linked issue says it will include plist in macOS tarballs. If I'm not mistaken, that means this https://github.com/mongodb/homebrew-brew/blob/34bfa124715ea174472c331ec0151052d885749f/Formula/mongodb-community.rb#L11 ?
This tgz contains no plist inside.

**Comment by dmoody256** [comment]
@crimsonvspurple The plist change (finished on March 20) did not make it in time for the 6.0.5 release, according to https://jira.mongodb.org/browse/SERVER-74156 (following the linked issues from [SERVER-74025](https://jira.mongodb.org/browse/SERVER-74025)), the back port of packaging the plist file will be in the 6.0.6 release.

We have plist available in the recent 4.4 and 5.0 releases, but the formulae have not been updated yet to use it.

**Comment by crimsonvspurple** [comment]
Thank you for the update @dmoody256 .

if 6.0.6 isn't going to be release really soon, maybe updating this page with a notice would be a good idea. https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/#run-mongodb-community-edition

**Comment by dmoody256** [comment]
@crimsonvspurple @lucasefe per #183 the service is now launched with plist and includes the extra launch options resource limits.

**Comment by elkwaet** [comment]
Reporting a regression relative to what this PR shipped.

This PR's diff sets:

```ruby
service do
  run [opt_bin/"mongod", "--config", etc/"mongod.conf"]
  working_dir HOMEBREW_PREFIX
  log_path var/"log/mongodb/output.log"
  error_log_path var/"log/mongodb/output.log"
end
```

but the current `Formula/mongodb-community.rb` on `master` has:

```ruby
service do
  name macos: "#{plist_name}"
end
```

with no `run` directive — while `install` still ships a full, correct `macos_mongodb.plist` into the keg (via `prefix.install_symlink "macos_mongodb.plist" => "#{plist_name}.plist"`).

On Homebrew 6.0.15 (Intel prefix), this `name macos:`-only block does not resolve to the keg's shipped plist. `brew services start mongodb-community` (and `brew reinstall`) writes an empty plist to `~/Library/LaunchAgents/homebrew.mxcl.mongodb-community.plist`:

```xml
<key>ProgramArguments</key>
<array/>
```

`launchctl bootstrap` then fails with an I/O error (exit 5), and the service never starts (`brew services list` shows `none`/not running).

Workaround: manually copy the keg's `macos_mongodb.plist` to `~/Library/LaunchAgents/` and load it via `launchctl bootstrap` directly — it's a correct, complete plist, just not the one `brew services` picks up.

Given the keg already ships a valid plist, restoring an explicit `run [...]` (as in this PR) or pointing the `service` block at the shipped plist file would fix this without needing to hand-edit LaunchAgents.

Environment: Homebrew 6.0.15, macOS (Darwin 24.2.0), `mongodb-community` 8.3.7 (also reproduced on 8.2.7).

**Pull request merged**
