### PR TITLE
Added the missing import

### PR DESCRIPTION
**Pull request by lincoln-b**
This is for https://github.com/mongodb/homebrew-brew/issues/6.

### CODE REVIEW

**Comment by chasinglogic** [comment]
Hey @lincoln-b,

Thanks for the pull request, would you mind adding this to all the Formula? Based on the comments on #6 it seems like this effects every version.

Thanks!

**Comment by lincoln-b** [comment]
I don’t believe the issue exists in other versions of the formula, because I don’t see the rubygems classes being used there — but I can take a look later when I’m on a computer!

**Comment by chasinglogic** [comment]
@lincoln-b You're totally correct, I'm new to this repo so still familiarizing myself with the code base.

Thanks! I'll merge this once I'm in office.

**Comment by chasinglogic** [comment]
Hey @lincoln-b,

Just got into the office and I saw that you haven't signed our CLA. You can find it here for digital signature: https://www.mongodb.com/legal/contributor-agreement

Once you've done that I can merge this PR.

**Comment by lincoln-b** [comment]
Signed it

**Comment by chasinglogic** [comment]
Awesome, thanks again for your help on this!

**Pull request merged**
